### ISSUE TITLE
Modified files does not open up

### ISSUE THREAD

**Issue by fusillicode** [hmatsuda/open-git-modified-files#5]
Hi, after a brand new installation of Atom, by both selecting the package command from the list opened by `cmd+p` / `ctrl+p` and using the default keyboard shortcut nothing happens.

Here are the required info asked by the contributing guidelines of this repository

```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

Sincerely I don't think I'm using the React Editor.

**Comment by fusillicode** [comment]
Thanks a lot for the quick fix! Waiting for the version bump. 👍

**Comment by hmatsuda** [comment]
@fusillicode Thanks for reporting this issue. 0.2.3 is available now.

**Comment by fusillicode** [comment]
My pleasure and once again thanks for the incredible fast fix. 👍
